# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Danielle Yamane
tagline:          '24'
description:      'A site filled with my thoughts and experiences curated for your enjoyment.'
url:              http://yamanedk.github.io

author:
  name:           'Danielle'
  url:            https://twitter.com/msjapexican

paginate:         5

# Custom vars
#version:          2.0.1

github:
  repo:           https://github.com/yamanedk/yamanedk.github.io
